"""add Rates table

Revision ID: 5db9edd2b5eb
Revises: 7fed3a5f998f
Create Date: 2026-07-19 12:53:08.353035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5db9edd2b5eb'
down_revision = '7fed3a5f998f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commute_rate', sa.Float(), nullable=False),
    sa.Column('mile_reimbursement', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rates')
    # ### end Alembic commands ###
