"""added is_active to Rates table

Revision ID: 8ca64e6c6fe3
Revises: 5db9edd2b5eb
Create Date: 2026-07-19 13:03:22.511774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ca64e6c6fe3'
down_revision = '5db9edd2b5eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rates', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
