"""commuteLog table

Revision ID: b99f552b1135
Revises: 2a8ea464268f
Create Date: 2026-07-17 18:32:31.373493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b99f552b1135'
down_revision = '2a8ea464268f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commute_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('mileage', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('commute_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commute_log_employee_id'), ['employee_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commute_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commute_log_employee_id'))

    op.drop_table('commute_log')
    # ### end Alembic commands ###
