"""add pay_rate to Employee table

Revision ID: d95873f920d9
Revises: b99f552b1135
Create Date: 2026-07-18 12:19:15.348964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd95873f920d9'
down_revision = 'b99f552b1135'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'pay_rate', sa.Float(), nullable=False, server_default="0"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('pay_rate')

    # ### end Alembic commands ###
